version: "3.8"

services:

  edge_1:
    container_name: edge_1
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=1  
    ports:
      - "5001:5000"
      - "8001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_2:
    container_name: edge_2
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=2
    ports:
      - "5002:5000"
      - "8002:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_3:
    container_name: edge_3
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=3
    ports:
      - "5003:5000"
      - "8003:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_4:
    container_name: edge_4
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=4
    ports:
      - "5004:5000"
      - "8004:8000"

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_5:
    container_name: edge_5
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=5
    ports:
      - "5005:5000"
      - "8005:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_6:
    container_name: edge_6
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=6
    ports:
      - "5006:5000"
      - "8006:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_7:
    container_name: edge_7
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=7
    ports:
      - "5007:5000"
      - "8007:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_8:
    container_name: edge_8
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=8
    ports:
      - "5008:5000"
      - "8008:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_9:
    container_name: edge_9
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=2
    ports:
      - "5009:5000"
      - "8009:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  edge_10:
    container_name: edge_10
    image: lightgbm-container:latest
    environment:
      - CONTAINER_ID=10
    ports:
      - "5010:5000"
      - "8010:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


volumes:
  ganache_data: